### ISSUE TITLE
[Bug:] Script is evaluated & executed although its predecessor isn't true

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#414] opened 2021-12-18 22:20 UTC
**Bug Description**
An image tells more than thousand words:
![Screenshot_20211218-132021](https://user-images.githubusercontent.com/25401767/146655586-eb123ad0-e7dc-4c93-b56a-5d2fe44f14cc.png)
As you can see, the profile "no day off" was evaluated as true (as well as its children) although its only predecessor "weekdays" was evaluated as false (which was correct, because the screenshot was taken this saturday which indeed is a weekend day, not a weekday).

**To Reproduce**
1) Just download my settings from here:
[Easer.2021-12-15.10_46_08 --- DailyRoutineBug.zip](https://github.com/renyuneyun/Easer/files/7740010/Easer.2021-12-15.10_46_08.---.DailyRoutineBug.zip)
2) Import them.
3) Start Easer.
4) Wait (Easer ran at least one day before the bug appeared, so guess it happens if the day before was a weekday and the current day is weekend/saturday).
5) Enjoy the bug!

**Expected behavior**
My expectation iis that a script isn't evaluated unless at least one of its direct predecessors was evaluated as true, i.e. there has to be a chain of (only) hreen dots/"LEDs" up to the root.

**Error log:**
Unfortunately, I hadn't activated the error log.
Now I did, and I will add one if the bug happens next time.

**Extra phone info (please complete the following information):**
 - ArrowOS 11
 -  Poco X3
 - rooted by Magisk

**Comment by just-Nob** [comment] 2021-12-23 18:58
Oh, I forgot to mention the version Easer:
It's v. 0.8.2.1.

**Comment by racuna** [comment] 2022-01-23 03:31
Im having the same issue recently

**Comment by racuna** [comment] 2022-01-24 15:57
Update: I disabled the Scripts with the issues, but they are still being evaluated. So, the problem occurs not only if the parent is false.

**Comment by samschr** [comment] 2022-01-30 16:32
0.8.2 , similar setup, same issue. I have Easer turn off my ringer 7am-4pm during working hours, with a predecessor condition that it only triggers during Mon-Fri weekdays. Works perfectly during the week, but on Saturday and Sunday my ringer still gets silenced.

![Screenshot_20220130-102707_Easer_1](https://user-images.githubusercontent.com/12620701/151708214-8fc15dfb-2d27-4704-bfab-327487bdccb7.png)

**Comment by racuna** [comment] 2022-01-31 14:17
Maybe off topic. But I have a question. 

If a Script have Two predecessors, It is considered an OR or an AND?

Anyway, in those cases, maybe the user should consider reverting the order of predecessor - successor if possible

e.g:

[A] [B]
  \   /
   [C]

to

   [C]
  /   \
[A] [B]

In the first case: if A and B are true, then C should be evaluated? Or, if A OR B are true, C would be evaluated? After changing the order (C then A/B) it is easier to understand it. IMHO: If C is true, then A and B could be evaluated separately.

But, since it is possible in Easer to have two or more predecessors, I had curiosity to know how it is handled

**Comment by eandersons** [comment] 2022-03-24 06:25
@racuna, I recently was curious about the same thing, so I made a quick and simple test and it seems that only one of parents have to be true for child script to be executed.

**Comment by just-Nob** [comment] 2022-03-24 16:14
Well, that's true, it is a logical or.
I already made the proposal to make it configurable (so that one of able to choose betweenAND/OR), see #393 for details.

**Comment by renyuneyun** [comment] 2022-03-27 20:26
Hello. Sorry for the delay. This is indeed a very useful bug report. Tracking this down, I found two related parts (one of them provides a hot fix; the other is the root cause).
The fix is included in the just-published v0.8.2.3-beta. Please report if it fixes this in your case(s) or not : )

p.s. The real reason also relates to multiple/repeated triggering of some script/profile at certain time (when it starts to listen and is true at that time). It only happens on some Conditions. I don't think there is an issue for that, but would like to mention this just in case.

**Comment by just-Nob** [comment] 2022-03-27 21:56
Thanks @renyuneyun  for these fixes. I'll try & report it asap.

**Comment by just-Nob** [comment] 2022-03-30 06:08
Hi @renyuneyun ,
will there be the 0.8.2.3-beta version on F-Droid?

**Comment by renyuneyun** [comment] 2022-04-01 22:22
@just-Nob Yes, it will. But unfortunately it fails to build at the moment (see [here for log](https://monitor.f-droid.org/builds/log/ryey.easer.beta/128001#site-footer)). See https://github.com/AppIntro/AppIntro/issues/1008 as I reported this issue to upstream.

**Comment by just-Nob** [comment] 2022-04-02 07:28
Hope that this will be fixed very soon.

**Comment by renyuneyun** [comment] 2022-04-16 11:15
Some update: no news yet, so I published a new beta version (v0.8.2.3-beta2) to work around this issue (changing the dependency version).

**Closed** 2022-04-23 16:51 UTC
Labels: bug
