### ISSUE TITLE
When I click on the "choose a condition" button, none of the date/time options work.

### ISSUE THREAD

**Issue by sargoon** [renyuneyun/Easer#233] opened 2019-07-03 19:42 UTC
**Describe the bug**
When I click on the Conditions -> Choose a Condition -> Date/Time = none of the date/time options work.

**To Reproduce**
1. Open the app.
2. Click on the "Conditions" option.
3. Create a "Condition title".
4. Choose a condition and try selecting any Date/Time options.
5. You will see that you can't select any of them.

(You can also use screencast instead.)

**Expected behavior**
The Easer users must properly select the option they want from the Date/Time tab.

**Extra phone info (please complete the following information):**
- ROM: MIUI Global 10.3.6
- Android Version: Android 9.0

**Record of the Bug**
![QuerulousDenseBlacknorwegianelkhound-size_restricted](https://user-images.githubusercontent.com/34961616/60620391-c3d27f00-9de3-11e9-93f0-3f6a8dc073a6.gif)

**Comment by racuna** [comment] 2019-07-03 19:45
What version are you? I don't have that problem on 0.7.6.1, but I can't update Easer because #228

**Comment by sargoon** [comment] 2019-07-03 20:01
> 
> 
> What version are you? I don't have that problem on 0.7.6.1, but I can't update Easer because #228

I'm using latest version, I just updated Easer today.

**Comment by X-dark** [comment] 2019-07-04 12:05
I got the same in 0.7.7.4 for any condition or event, using Android 9 as well.

**Comment by BernardOOO** [comment] 2019-07-08 12:04
hi,
same issue here with 0.7.7.4 on Nexus 6P running LineageOs 15.1 and on Nexus 5 running LineageOs 14.1.

**Comment by sargoon** [comment] 2019-07-08 12:41
Hi @renyuneyun, can you please check?

**Comment by renyuneyun** [comment] 2019-07-14 10:42
Hi guys,
You are right it's a bug. I published v0.7.7.5 last night and it should fix this.

I'll wait for a few days before closing issue\, in case it's not solved in v0.7.7.5

**Comment by sargoon** [comment] 2019-07-21 22:31
Hi there, the problem still continues. :(

**Comment by renyuneyun** [comment] 2019-08-09 11:33
Hi @sargoon , could you try some other versions (e.g. v0.7.7.6, v0.7.8-beta) to see if any of them fixes this?

This is no longer a bug on my side and the cause was quite straightforward... It's confusing to see it not fixed on some devices and fixed on some other devices...

**Comment by renyuneyun** [comment] 2019-12-22 22:04
I'm closing this because of long inactivity, so I'm assuming a version solving this should have been working. Please open a new issue if otherwise, and link to this issue.

**Closed by renyuneyun** 2019-12-22 22:04 UTC
Labels: bug, fixed?
