### ISSUE TITLE
Events with periodisity

### ISSUE THREAD

**Issue by yamatt** [renyuneyun/Easer#16] opened 2017-06-26 06:37 UTC
Hi. I would really like to be able to toggle my WiFi every 10 minutes. The current way of doing that would to be to create a lot of events for every 10 minutes over the day.

Could you add an option to run an event every X minutes?

**Comment by ildar** [comment] 2017-06-26 06:51
In the meanwhile you can use WiFi Automatic (Turn off WiFi automatically) -
https://f-droid.org/app/de.j4velin.wifiAutoOff for that

**Comment by yamatt** [comment] 2017-06-26 16:38
@ildar hi. Thanks for that. I'll look in to it, but the WiFi was an example, so it's probably a bit too specific for my needs.

**Comment by renyuneyun** [comment] 2017-06-27 12:16
Yup, I like this idea :)

Actually I've thought about it once, but can't decide the proper semantics for this kind of events. Suggestions wanted:

Currently events are tree-structured. A child event will be checked only after all its parents (parent, grandparent, ...) are satisfied. Each event (together with its type) has a mark to control whether its child events should be sticky / put into top level (e.g. **exactly at** a time will have a different mark than **after** a time).
Are there any ways to keep the current semantics and add the ability to control something (and reverse it) after some time? I can think of the situation that we may want to open wifi every 10 minutes to sync data and then (maybe 5 minutes later) close it to save battery.
If the old semantics can't satisfy the new need, how should the new semantics be designed?

**Comment by yamatt** [comment] 2017-06-27 18:24
@renyuneyun I would think it would just be a new event type like "TIme" and "Date", and the "repeating" event would simply be an integer that runs on an integer, every x minutes or x hours.

**Comment by renyuneyun** [comment] 2017-07-03 22:03
@yamatt Then what about reversing / reverting or pairing that operation?

I mean, for example, turn on WiFi every 10 minutes, and then turn it off 2 minutes later.

I'm still not sure about what the semantics should be...

**Comment by ksamak** [comment] 2017-12-07 09:32
Hi, just bumping log to get the follow up in the thread.

**Comment by renyuneyun** [comment] 2017-12-22 00:28
Finally, that is implemented :)>
They are added in v0.5. (Thought due to a strange f-droid bug, the date when v0.5 enter the repo is unpredictable... Maybe a few days later, maybe weeks...)

The implementation is in the form of a "timer" which simply delays the detection and execution of its successors.

Therefore, if we want to connect to cellular network for 1 minute and then sleep for 10 minutes, the senario will be:
0. Add an event (*A*) checking that we have left home
1. Add an event checking the network type is cellular, and set the parent to *A*
  1.5. Add an event using timer of 1 minute, and active a profile which turns cellular data off
2. Add an event checking the network type is not cellular (or "none" or everything else if you like), and set the parent to *A*
  2.5. Add an event using timer of 10 minute, and active a profile which turns cellular data on

They will work as intended in principle :)

I'm closing this issue. Feel free to open new issues if that doesn't work well.

**Closed by renyuneyun** 2017-12-22 00:28 UTC
Labels: discussion wanted, feature request
