### ISSUE TITLE
cooldown and repeatable is ignored?

### ISSUE THREAD

**Issue by kaefert** [renyuneyun/Easer#134] opened 2018-07-01 08:45 UTC
I've tried setting cooldown to 0 and 1 and I've activated the "Repeatable when satisfied"-slider in the script but still I cannot trigger my Event->Script->Profile chain when it has been triggered within the last at least 5 hours.

Did I misunderstand those settings or is there a bug? Can you explain how I can make Easer activate the Event->Script->Profile chain every time the input broadcast is detected, no matter how long ago it has been detected the last time?

Thank you!

**Comment by renyuneyun** [comment] 2018-07-05 22:23
Thanks for reporting this. I think it should work in your description.
(One thing not important to this question, but you probably want to know: I make a wrong check of cooldown time in the code, which treats the input number as milliseconds.)

Your configuration is correct. Setting the Script as "repeatable when satisfied" is the only thing needed. (Actually I should make this the default selection.)
Is that Script set as "volatile"? It should be both "volatile" and "repeatable when satisfied".

**Comment by kaefert** [comment] 2018-07-06 05:03
Yes it is both "volatile" (slider = to the left & gray) and "repeatable when satisfied" (slider = to the right & red), but it still won't execute again, if it has been executed within the last few hours.

**Comment by kaefert** [comment] 2018-07-07 11:33
btw, since you mentioned that you unintentionally treated the cooldown time as milliseconds: What unit did you intend it to have? Maybe you could rename it from "cooldown" to "cooldown in hours" (or whichever unit you want it to have).

**Comment by renyuneyun** [comment] 2018-07-07 13:18
Hmm, that's strange. I'll investigate.

Which Event are you using for this case?


("Second" is the intended unit, and the default value is 3 seconds.)

**Comment by renyuneyun** [comment] 2018-07-08 17:09
Hmm... I can't reproduce the problem.

My test case:

0. Easer v0.6.6; Cooldown time is 5
1. In Easer, try to receive Broadcast with `action=ryey.action` and `category=ll.c`
2. Open adb shell, execute `am broadcast -a ryey.action -c ll.c` to send the broadcast

It works as expected (except for that the cooldown is mis-treated as milliseconds in this version). Everytime I execute the command, the corresponding Profile is loaded (I use a notification).

**Comment by kaefert** [comment] 2018-07-14 09:43
Hmmm.. Strange. Using the `am broadcast` command I can't get Easer to see the broadcast at all.
Using the Gadgetbridge way after a long time of no usage I can make Easer to see it:
https://pastebin.ubuntu.com/p/XB6Jp3kz3c/

doing the same a bit later doesn't work:
https://paste.ubuntu.com/p/qXJkdXq79H/

**Comment by renyuneyun** [comment] 2018-07-15 00:17
So, from the first log, it shows that Easer successfully caught the broadcast, but failed to load the Profile.

Maybe you should check your Profile used there (`ringNow`).
If you can't discover, would you mind showing you Profile `ringNow`?

**Comment by renyuneyun** [comment] 2018-11-02 00:20
Hi,
Finally, this should have been fixed now.
Very accidentally, I figured out why repeatable is ignored...

The error in the log was about Dynamics, which is also fixed.


I think this can now be closed?

**Comment by renyuneyun** [comment] 2019-07-21 18:40
Since there is no more activity, I'm closing this issue for now.
If this is still a thing, please feel free to re-open.

**Closed by renyuneyun** 2019-07-21 18:40 UTC
Labels: bug, fixed?, going-to-be-closed?
