### ISSUE TITLE
Send Broadcast seems not to work

### ISSUE THREAD

**Issue by immae** [renyuneyun/Easer#151] opened 2018-08-10 11:52 UTC
The "Send broadcast" operation seems not to work.

I have a very simple broadcast to run, with only an action. If I put it as a broadcast, it never get sent.
As a workaround I can make a "Run command" `am broadcast -a app.ACTION` which works correctly.

I don’t know how to provide for logs but I have the tools to make them (adb / logcat / root) if you tell me what you need.

**Comment by renyuneyun** [comment] 2018-08-14 21:29
Hi there,
thanks for reporting. I'll investigate soon if I have time.
I guess this may relate to another issue but I never thought this may not work as expected (:o)

**Comment by renyuneyun** [comment] 2018-09-17 22:51
Sorry for the long delay.
Actually I can't reproduce the bug. Sending broadcasts works on the devices I tested.
Could you provide an example broadcast which you didn't get to work?

**Comment by immae** [comment] 2018-09-21 22:59
Hi @renyuneyun The application is the `sms backup +` application, and the intent is the action that triggers a backup.

Note that the "Run commands" profile "am broadcast -a com.zegoggles.smssync.BACKUP" makes the job, while the "Send broadcast" with the corresponding parameters does nothing at all. This makes me think that the problem is in Easer and not the other app, since a command is able to run the intent.
But I may have missed some mechanisms.
Please tell me if I can be of any help.

**Comment by renyuneyun** [comment] 2018-10-08 23:36
Aha, I finally figured out the problem, and this should be fixed in the next release ;p

**Closed** 2018-10-09 00:02 UTC
Labels: bug

**Comment by immae** [comment] 2018-10-10 06:37
Thanks for your investigation @renyuneyun ! I’ll test it as soon as it arrives in Fdroid :)
