### ISSUE TITLE
Feature request: Support for WireGuard VPN trigger

### ISSUE THREAD

**Issue by JafarKhQ** [renyuneyun/Easer#361] opened 2020-10-20 12:46 UTC
WireGuard Android app supports three actions
> com.wireguard.android.action.SET_TUNNEL_UP
> com.wireguard.android.action.SET_TUNNEL_DOWN
> com.wireguard.android.action.REFRESH_TUNNEL_STATES 

For security reasons automation apps needs to ask for permission to be able to trigger those actions:
> `<uses-permission` `android:name="com.wireguard.android.permission.CONTROL_TUNNELS"/>`

Then request the permission:
> ActivityCompat.requestPermissions(this, new String[]{"com.wireguard.android.permission.CONTROL_TUNNELS"}, someRequestNumber)

Reference: 
[WireGuard now supports control by remote apps](https://www.reddit.com/r/tasker/comments/fn6wou/wireguard_now_supports_control_by_remote_apps/fl93kw8/)
[Native Intents](https://www.reddit.com/r/WireGuard/comments/fnqysi/native_tasker_intents_new_in_app_mar_22_2020/)

**Comment by bontibon** [comment] 2021-04-24 18:15
CR #375

**Comment by renyuneyun** [comment] 2021-05-02 17:43
#375 is merged, and is included in v0.8.2-beta (which should appear in a few days) :) Thanks @bontibon !

Please have a test and report back. If nothing wrong happens, I'll close this issue when moving to v0.8.2 (non-beta release).

**Comment by renyuneyun** [comment] 2021-05-14 21:57
Hi @khimaros , thanks for noticing that. I'll have a test soon when I have time, and provide a fix or an explanation afterwards.
In the meantime, I have quoted this to a new issue #377 , and would hope to do further discussion there :)

**Comment by Xerono** [comment] 2021-07-22 23:43
I've set up Easer (Beta) from the F-Droid store to activate Wireguard once I'm not connected to my home wifi. Sometimes, Wireguard gets started, but I don't get a connection, even if mobile data is working. I can't really reproduce it and it's happening on two different phones. Manually turning off the tunnel and turning it on again fixes the problem. It's happening in about 1/4 tries, 3/4 times it works as expected. I'm testing this with simply turning my wifi on the router off, but it happens when leaving the house, too.

 My setup is the following:

**Data:**
_Activate- Wireguard_

- Profile: Wireguard active
- Reverse Scenario is enabled
- Condition: Home-Wifi

_Dectivate- Wireguard_

- Profile: Wireguard inactive
- Reverse Scenario is disabled
- Condition: Home-Wifi

**Condition:**
_Home-Wifi_

- Match BSSID (MAC) with my MAC (the radio box is not activated, but it still works this way, so it's probably just a visual bug)

**Profile:**
_Wireguard active_

- Set Tunnel State (My tunnel) Up
_Wireguard inactive_

- Set Tunnel State (My tunnel) Down

I assumed the problem was that Wireguard gets activated before a new network connection gets started, so I added another Condition which checks if I'm not connected to a network, activated "Reverse Scenario" for it in a new script and used that script as a predecessor for my "Activate Wireguard" script, but this doesn't solve the problem.

**Comment by khimaros** [comment] 2021-07-23 00:10
i experience the same issue. it may be a bug with wireguard itself.

**Comment by id4vip** [comment] 2021-08-10 16:48
Please somebody guide me to make a profile in easer for controlling wireguard. i am able to configure wifi conditions. everything works fine. but not able to understand the profile portion to on off wireguard app & wireguard tunnel "myhome
"

**Closed** 2021-08-15 16:59 UTC

**Comment by maurerle** [comment] 2023-08-06 07:19
It is important to set "App battery usage" of the wireguard android app to unrestricted.
I wondered for a long time if my profile name is somehow wrong, because nothing happened.

Furthermore, in the pivot view, long press on the profile allows to trigger it directly, which makes debugging much easier
