### ISSUE TITLE
NullPointerException when pressing Script/New/Profile/🔗

### ISSUE THREAD

**Issue by jimbo1qaz** [renyuneyun/Easer#147] opened 2018-07-21 06:12 UTC
0.6.7.2 from F-Droid.

I don't know how Easer works. I'm trying to create a Script (the first item on the sidebar), but it won't let me save because "Prevented saving data with invalid field(s)."

If I have to define events before scripts, maybe the Script editor should allow me to create events directly from the editor... Or maybe the sidebar should place events before scripts.

In the Profile category, there is a chainlink button. Clicking causes the following error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'ryey.easer.commons.plugindef.eventplugin.EventData ryey.easer.core.a.b.b()' on a null object reference
	at ryey.easer.core.ui.data.EditScriptActivity$2.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5612)
	at android.view.View$PerformClick.run(View.java:22288)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

I suspect the unintuitive UI (I still don't know what triggers exist, nor what actions can be taken upon triggers) is a more fundamental problem. I don't know what that button does, nor what I should add to make the button not crash.

**Comment by jimbo1qaz** [comment] 2018-07-21 06:33
My idea is to setup the sidebar with numbered events:

- Step 1: Events
- Step 2: Profiles
- Step 3: Conditions
- Step 4: Scripts

(I think plural is better)

**Comment by ildar** [comment] 2018-07-21 06:40
What version is crashing?
Latest version is said to have fix for similar problem

**Comment by jimbo1qaz** [comment] 2018-07-21 06:40
i edited my main post with the version number

**Comment by renyuneyun** [comment] 2018-07-21 16:03
So, generally, you can read [this page in the wiki](https://github.com/renyuneyun/Easer/wiki/Usage-example) and #62  for a basic understanding of how to use Easer.

I couldn't reproduce the crash when clicking the "chainlink" button, as this should have been fixed in v0.6.7.2...
Could you send a screenshot of the page which will crash when clicking this button?

**Comment by jimbo1qaz** [comment] 2018-07-21 20:37
![](https://i.imgur.com/L0Z4sOJ.png)

Crash only happens if zeero events are defined. Clearing app data is an easy way for me to reproduce.

**Comment by ildar** [comment] 2018-07-23 05:02
can also send the logcat?

**Closed** 2018-08-05 22:32 UTC
Labels: bug

**Comment by renyuneyun** [comment] 2018-08-05 22:38
I assume the screenshot doesn't exactly corresponds to your problem, as stated in the sentence ("if zero events are defined").

If so, v0.6.9 should have fixed this problem :)
